In [121]:
with open('ex.txt','r') as file:
    cont=file.read()
    print(cont)

hello world fuck u 
append
 fisrt
second
third



In [30]:
## this method overwrites not usefull
with open('ex.txt','w') as file:
    file.write("hello world fuck u \n")

In [31]:
## use this instead
with open('ex.txt','a') as file:
    file.write("append\n ")

In [32]:
##writing list of lines 
lists=['fisrt\n','second\n','third\n']
with open('ex.txt','a') as file:
    file.writelines(lists)

In [33]:
import os
new_direc="package"
os.mkdir(new_direc)
print(f"directory '{new_direc}'")


FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'package'

In [ ]:
items=os.listdir('.')
print(items)

['ex.txt', 'package', 'py.ipynb']


In [ ]:
## joining path
dir_name="folder"
file_name="file.txt"
full_path=os.path.join(dir_name,file_name)
print(full_path)

folder\file.txt


In [ ]:
dir_name="folder"
file_name="file.txt"
full_path=os.path.abspath(file_name)
print(full_path)

c:\Users\saumya pathak\Desktop\python\course\file.txt


In [ ]:
po=int(input("enter the number"))


In [ ]:
class car:
    def Engine(self):
        print("car is started")
        
obj1=car()
obj1.Engine()

car is started


In [ ]:
from abc import ABC,abstractmethod

class vehicle(ABC):
    def drive(self):
        print("driving")
    @abstractmethod
    def start_eng(self):
        pass
    
class car(vehicle):
    def start_eng(self):
        print("car eng started")
        
def operate_vehicle(vehicle):
    vehicle.start_eng()
    
Car = car()
operate_vehicle(Car)

car eng started


In [ ]:
mylist=[1,2,3,4]

iterator=iter(mylist)

try:
    print(next(iterator))
except StopIteration:
    print("there are no elements left in the list")
    

1


In [ ]:
mylist=[1,2,3,4]

iterator=iter(mylist)
while True:

    try:
        print(next(iterator))
    except StopIteration:
        print("there are no elements left in the list")
        break

1
2
3
4
there are no elements left in the list


generators


In [36]:
def square(n):
    for i in range(3):
        yield i**2

In [37]:
square(3)

<generator object square at 0x000001BBE9772B50>

In [38]:
### funtion copy example
def welcome():
    print("welcome to vs code")
    
welcome()

welcome to vs code


In [41]:
## now if we make its object and delete the main function
wel=welcome

In [43]:
## here u see even after deleting the main
## funtion we are still able to access it from its object
## this is called funtion copy
wel()
del welcome
wel()

welcome to vs code
welcome to vs code


In [48]:
## closures-func inside func
def main_wel():
    msg="wwelcome"
    def sub_wel():
        print(f"saumya {msg}")
    return sub_wel()

In [49]:
main_wel()

saumya wwelcome


In [52]:
def main_wel(func):
    def sub_wel():
        print(f"saumya ")
        print(func("please understand"))
    return sub_wel()

In [54]:
main_wel(print)

saumya 
please understand
None


In [ ]:
### decorator
def main_wel(func):
    def sub_wel():
        print(f"saumya ")
        print(func())
    return sub_wel()

In [55]:
def course_intro():
    print("this is an python c")

In [56]:
course_intro()

this is an python c


In [59]:
main_wel(course_intro)

saumya 
this is an python c
None


In [63]:
''' decorator is a function that
takes another function as input, adds some functionality
to it, and returns a new function — all without modifying
the original function’s code.'''
@main_wel
def course_intro():
    print("this is an python c")

saumya 
this is an python c
None


In [74]:
class countdown:
    def __init__(self,start):
        self.current=start
    def __iter__(self):
        return self
    def __next__(self):
        if self.current<=0:
            raise StopIteration
        else:
            self.current-=1
            return self.current

In [65]:
countdown(4)

In [75]:
for i in countdown(5):
    print(i)

4
3
2
1
0


In [81]:
class my_range:
    def __init__(self,start,end):
        self.current=start
        self.end=end
        
    def __iter__(self):
        return self
    def __next__(self):
        if self.current>=self.end:
            raise StopIteration
        else:
            self.current+=1
            return self.current-1

In [82]:
for i in my_range(0,5):
    print(i)

0
1
2
3
4


In [85]:
## generator
def feb(n):
    a, b=0, 1
    for _ in range(n):
        yield a
        a, b=b, a+b


<generator object feb at 0x000001BBE98320A0>


In [87]:
for i in feb(22):
    print(i)

0
1
1
2
3
5
8
13
21
34
55
89
144
233
377
610
987
1597
2584
4181
6765
10946


In [110]:
# List: creates all numbers at once (uses more memory)


# Generator: creates numbers one-by-one (very memory-efficient)
def square_gen(n):
    for x in range(n):
        yield x*x
        



In [ ]:
gen = square_gen(5)

while True:
    try:
        print("your current element is:")
        print(next(gen))
    except StopIteration:
        print("no more values left")
        break

your current element is:
0
your current element is:
1
your current element is:
4
your current element is:
9
your current element is:
16
your current element is:
no more values left


your current element is:
0
your current element is:
1
your current element is:
4
your current element is:
9
your current element is:
16
your current element is:
no more values left


In [ ]:
def even_numbers(n):
    for i in range(n + 1):
        if i % 2 == 0:
            yield i

def sq(k):
    for i in k:
        yield i * i

gen1 = even_numbers(20)
gen2 = sq(gen1)

for i in gen2:
    print(i)


0
4
16
36
64
100
144
196
256
324
400


In [120]:
print("hello")

hello


In [1]:
def repeat(n):
    def decorator(func):
        def wrapper(*args,**kwargs):
            for _ in range(n):
                func(*args,**kwargs)
        return wrapper
    return decorator

@repeat(3)
def gh(n):
    return n**2

print(gh(4))

None


In [2]:
def uppercase(cls):
    class Wrapped(cls):
        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.data = self.data.upper()
    return Wrapped

@uppercase
class ReverseString:
    def __init__(self, data):
        self.data = data
        self.index = len(data)

    def __iter__(self):
        return self

    def __next__(self):
        if self.index == 0:
            raise StopIteration
        self.index -= 1
        return self.data[self.index]

# Test
for char in ReverseString("hello"):
     print(char)

O
L
L
E
H


In [9]:
## counter takes value and increments by one
def count(num):
    current=num
    while True:
        yield current
        current+=1
        
ct=count(0)
for _ in range(10):
    print(next(ct))

0
1
2
3
4
5
6
7
8
9


In [11]:
def lk(lst,d):
    for i in lst:
        try:
            yield i/d
        except ZeroDivisionError as zd:
            print("please check the the diviser")
            
lst=[3,6,9]
for result in lk(lst,0):
    print(result)

please check the the diviser
please check the the diviser
please check the the diviser


In [15]:
import time

def timer(func):
    def wrapper(*args,**kwargs):
        start=time.time()
        result = func(*args,**kwargs)
        end=time.time()
        print(f"this process took {end-start} time /n")
        return result
    return wrapper
@timer
def example(n):
    time.sleep(n)
    
example(2)
    
    

this process took 2.00044584274292 time /n


In [17]:
%pip install numpy

  Using cached numpy-2.2.6-cp312-cp312-win_amd64.whl.metadata (60 kB)
Using cached numpy-2.2.6-cp312-cp312-win_amd64.whl (12.6 MB)
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [21]:
import numpy as np

arr=np.array([1,2,3,4,5])
print(arr)
type(arr)
print(arr.shape)

[1 2 3 4 5]
(5,)


In [27]:
arr1=np.array([[1,2,3,4,5],[2,3,4,5,6]])
arr1.shape

(2, 5)

In [28]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [29]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [32]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
## some numpy operations

arr=np.array([1,2,3,4])

print(np.square(arr))

print(np.exp(arr))

print(np.sin(arr))

print(np.log(arr))

[ 1  4  9 16]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[0.         0.69314718 1.09861229 1.38629436]


In [40]:
## slicing and indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print(arr)

arr[0][3]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


np.int64(4)

In [42]:
arr[1][2]

np.int64(7)

In [56]:
arr[1:,1:3]

array([[ 6,  7],
       [10, 11]])

In [57]:
## modify elements

arr[0][0]=100

In [58]:
arr

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [ ]:
arr[1:]=[56,12,34,56]

In [60]:
arr

array([[100,   2,   3,   4],
       [ 56,  12,  34,  56],
       [ 56,  12,  34,  56]])

In [63]:
arr[1]=[23,34,56,73]

In [64]:
arr

array([[100,   2,   3,   4],
       [ 23,  34,  56,  73],
       [ 56,  12,  34,  56]])

In [71]:
### normalization
my_arr=np.array([[1,2,3,4]])

print(np.mean(my_arr))

print(np.median(my_arr))

print(np.std(my_arr))

print(np.var(my_arr))

2.5
2.5
1.118033988749895
1.25


In [72]:
pip install pandas

^C
Note: you may need to restart the kernel to use updated packages.


  Using cached pandas-2.2.3-cp312-cp312-win_amd64.whl.metadata (19 kB)
  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
  Using cached tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Using cached pandas-2.2.3-cp312-cp312-win_amd64.whl (11.5 MB)
Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
Using cached tzdata-2025.2-py2.py3-none-any.whl (347 kB)



[notice] A new release of pip is available: 24.0 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
import pandas as pd


In [2]:
## series

data=[1,2,3,4,5]
series=pd.Series(data)
print(series)


0    1
1    2
2    3
3    4
4    5
dtype: int64


In [3]:
data={'a':1,'b':2,'c':3}

dat=pd.Series(data)

print(dat)

a    1
b    2
c    3
dtype: int64


In [6]:
data={'name':['saumya','sarika','disha'],
      'age':[20,49,44],
      'city':['godhra','delhi','vadodra']}

kj=pd.DataFrame(data)
type(kj)
print(kj)

     name  age     city
0  saumya   20   godhra
1  sarika   49    delhi
2   disha   44  vadodra


In [8]:
## create a df from a list of the dictionaries
data=[{'name':'saumya','age':32},
       {'name':'sarika','age':31},
        {'name':'disha','age':22}]

kj=pd.DataFrame(data)
type(kj)
print(kj)

     name  age
0  saumya   32
1  sarika   31
2   disha   22


In [12]:
df=pd.read_csv('sampledata.csv')
df.tail(5)
df.head(3)

ID     Name  Age  Subject  Score
0   1    Alice   20     Math     85
1   2      Bob   21  English     78
2   3  Charlie   22  Science     92

In [17]:
## accesing
df['Score']

0    85
1    78
2    92
3    67
4    74
5    88
6    81
7    90
8    69
9    95
Name: Score, dtype: int64

In [19]:
df.at[1,'Age']

np.int64(21)

In [20]:
df.iat[1,1]

'Bob'

In [21]:
df

ID     Name  Age  Subject  Score
0   1    Alice   20     Math     85
1   2      Bob   21  English     78
2   3  Charlie   22  Science     92
3   4    Daisy   20  History     67
4   5    Ethan   23     Math     74
5   6    Faith   21  English     88
6   7   George   22  Science     81
7   8   Hannah   20  History     90
8   9      Ian   21     Math     69
9  10     Jane   23  English     95

In [24]:
df['salary']=[3000,4000,5000,100,200,1000,2000,6000,7000,8000]
df

ID     Name  Age  Subject  Score  salary
0   1    Alice   20     Math     85    3000
1   2      Bob   21  English     78    4000
2   3  Charlie   22  Science     92    5000
3   4    Daisy   20  History     67     100
4   5    Ethan   23     Math     74     200
5   6    Faith   21  English     88    1000
6   7   George   22  Science     81    2000
7   8   Hannah   20  History     90    6000
8   9      Ian   21     Math     69    7000
9  10     Jane   23  English     95    8000

In [ ]:
## remove a coloumn
## if axis is zero i only checks the rows 
## and to confirm the deletion we have to 
##use inplace= trueS
df.drop('salary',axis=1,inplace=True)

In [30]:
df

ID     Name  Age  Subject  Score
0   1    Alice   20     Math     85
1   2      Bob   21  English     78
2   3  Charlie   22  Science     92
3   4    Daisy   20  History     67
4   5    Ethan   23     Math     74
5   6    Faith   21  English     88
6   7   George   22  Science     81
7   8   Hannah   20  History     90
8   9      Ian   21     Math     69
9  10     Jane   23  English     95

In [32]:
df.drop(df.tail(5).index,inplace=True)

In [33]:
df

ID     Name  Age  Subject  Score
0   1    Alice   20     Math     85
1   2      Bob   21  English     78
2   3  Charlie   22  Science     92
3   4    Daisy   20  History     67
4   5    Ethan   23     Math     74

In [34]:
import pandas as pd

In [40]:
df=pd.read_csv('statistics_sample.csv')

In [41]:
df.head(5)


ID  Age  Salary  Experience (Years)  Hours Worked/Week
0   1   25   50000                   2                 40
1   2   30   60000                   5                 45
2   3   22   45000                   1                 35
3   4   28   52000                   3                 40
4   5   35   75000                   8                 50

In [42]:
df.describe()

ID        Age        Salary  Experience (Years)  \
count  10.00000  10.000000     10.000000           10.000000   
mean    5.50000  29.800000  59200.000000            4.600000   
std     3.02765   5.159673  11341.173759            2.836273   
min     1.00000  22.000000  45000.000000            1.000000   
25%     3.25000  26.500000  50500.000000            2.250000   
50%     5.50000  29.500000  59500.000000            4.500000   
75%     7.75000  31.750000  61750.000000            5.750000   
max    10.00000  40.000000  80000.000000           10.000000   

       Hours Worked/Week  
count          10.000000  
mean           43.700000  
std             6.019413  
min            35.000000  
25%            40.000000  
50%            43.000000  
75%            47.250000  
max            55.000000

In [43]:
df.dtypes

ID                    int64
Age                   int64
Salary                int64
Experience (Years)    int64
Hours Worked/Week     int64
dtype: object

In [44]:
df.isnull()

ID    Age  Salary  Experience (Years)  Hours Worked/Week
0  False  False   False               False              False
1  False  False   False               False              False
2  False  False   False               False              False
3  False  False   False               False              False
4  False  False   False               False              False
5  False  False   False               False              False
6  False  False   False               False              False
7  False  False   False               False              False
8  False  False   False               False              False
9  False  False   False               False              False

In [45]:
df.isnull().any

<bound method DataFrame.any of       ID    Age  Salary  Experience (Years)  Hours Worked/Week
0  False  False   False               False              False
1  False  False   False               False              False
2  False  False   False               False              False
3  False  False   False               False              False
4  False  False   False               False              False
5  False  False   False               False              False
6  False  False   False               False              False
7  False  False   False               False              False
8  False  False   False               False              False
9  False  False   False               False              False>

In [46]:
df.isnull().sum()

ID                    0
Age                   0
Salary                0
Experience (Years)    0
Hours Worked/Week     0
dtype: int64

In [55]:
## renaming couloumn
df=df.rename(columns={'salary':'income'},inplace=True)

AttributeError: 'NoneType' object has no attribute 'rename'

In [56]:
print(df)

None


In [57]:
df=pd.read_csv('statistics_sample.csv')

In [58]:
df=df.rename(columns={'salary':'income'},inplace=True)

In [59]:
df

In [60]:
print(df)

None


In [20]:
import pandas as pd

In [21]:
tab1=pd.DataFrame({
                   'id':[1,2,3],
                   'name':['saumya','sarika','disha'],
                   'ocupation':['doctor','engineer','teacher']
                   })

tab1

id    name ocupation
0   1  saumya    doctor
1   2  sarika  engineer
2   3   disha   teacher

In [22]:
tab2=pd.DataFrame({
                   'id':[1,2,4],
                   'name':['saumya','sarika','jayesh'],
                   'ocupation':['doctor','engineer','accountant']
                   })

In [23]:
inner=pd.merge(tab1,tab2,on='id',how='inner')

In [24]:
inner

id  name_x ocupation_x  name_y ocupation_y
0   1  saumya      doctor  saumya      doctor
1   2  sarika    engineer  sarika    engineer

In [25]:
outer=pd.merge(tab1,tab2,on='id',how='outer')

In [26]:
outer

id  name_x ocupation_x  name_y ocupation_y
0   1  saumya      doctor  saumya      doctor
1   2  sarika    engineer  sarika    engineer
2   3   disha     teacher     NaN         NaN
3   4     NaN         NaN  jayesh  accountant

In [27]:
right=pd.merge(tab1,tab2,on='id',how='right')
left=pd.merge(tab1,tab2,on='id',how='left')

In [28]:
right

id  name_x ocupation_x  name_y ocupation_y
0   1  saumya      doctor  saumya      doctor
1   2  sarika    engineer  sarika    engineer
2   4     NaN         NaN  jayesh  accountant

In [29]:
left

id  name_x ocupation_x  name_y ocupation_y
0   1  saumya      doctor  saumya      doctor
1   2  sarika    engineer  sarika    engineer
2   3   disha     teacher     NaN         NaN

In [37]:
print(tab1.iloc[0]['name'])

saumya


In [39]:
tab1['name']

0    saumya
1    sarika
2     disha
Name: name, dtype: object

In [41]:
tab1=tab1.set_index('id')

In [42]:
tab1

name ocupation
id                  
1   saumya    doctor
2   sarika  engineer
3    disha   teacher

In [46]:
inner.head()

id  name_x ocupation_x  name_y ocupation_y
0   1  saumya      doctor  saumya      doctor
1   2  sarika    engineer  sarika    engineer

In [47]:
inner.tail()

id  name_x ocupation_x  name_y ocupation_y
0   1  saumya      doctor  saumya      doctor
1   2  sarika    engineer  sarika    engineer

In [48]:
inner.describe()

id
count  2.000000
mean   1.500000
std    0.707107
min    1.000000
25%    1.250000
50%    1.500000
75%    1.750000
max    2.000000

In [49]:
inner.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   id           2 non-null      int64 
 1   name_x       2 non-null      object
 2   ocupation_x  2 non-null      object
 3   name_y       2 non-null      object
 4   ocupation_y  2 non-null      object
dtypes: int64(1), object(4)
memory usage: 212.0+ bytes


In [51]:
inner.columns

Index(['id', 'name_x', 'ocupation_x', 'name_y', 'ocupation_y'], dtype='object')

In [54]:
inner.transpose()

0         1
id                1         2
name_x       saumya    sarika
ocupation_x  doctor  engineer
name_y       saumya    sarika
ocupation_y  doctor  engineer

In [ ]:
data = {
    'id': [1, 2, 3, 4, 5],
    'name': ['Saumya', 'Sarika', 'Disha', 'Ravi', 'Neha'],
    'age': [25, 30, 28, 22, None],
    'occupation': ['Doctor', 'Engineer', 'Teacher', 'Doctor', 'Engineer'],
    'salary': [70000, 80000, 50000, 72000, None],
    'city': ['Delhi', 'Mumbai', 'Delhi', 'Chennai', 'Mumbai']
}



In [58]:
ex1=pd.DataFrame(data)

In [59]:
ex1.describe()

id    age        salary
count  5.000000   4.00      4.000000
mean   3.000000  26.25  68000.000000
std    1.581139   3.50  12754.084313
min    1.000000  22.00  50000.000000
25%    2.000000  24.25  65000.000000
50%    3.000000  26.50  71000.000000
75%    4.000000  28.50  74000.000000
max    5.000000  30.00  80000.000000

In [60]:
ex1[ex1['salary'] > 72000]

id    name   age occupation   salary    city
1   2  Sarika  30.0   Engineer  80000.0  Mumbai

In [62]:
ex1[ex1['name'] == 'Sarika']

id    name   age occupation   salary    city
1   2  Sarika  30.0   Engineer  80000.0  Mumbai

In [66]:
ex1[ex1['salary'].isnull()]

id  name  age occupation  salary    city
4   5  Neha  NaN   Engineer     NaN  Mumbai

In [69]:
print(ex1[ex1['salary'].isnull()]['name'])

4    Neha
Name: name, dtype: object


In [70]:
ex1.set_index('id')

name   age occupation   salary     city
id                                           
1   Saumya  25.0     Doctor  70000.0    Delhi
2   Sarika  30.0   Engineer  80000.0   Mumbai
3    Disha  28.0    Teacher  50000.0    Delhi
4     Ravi  22.0     Doctor  72000.0  Chennai
5     Neha   NaN   Engineer      NaN   Mumbai

In [71]:
ex1.loc[0]

id                  1
name           Saumya
age              25.0
occupation     Doctor
salary        70000.0
city            Delhi
Name: 0, dtype: object

In [72]:
ex1.isnull()

id   name    age  occupation  salary   city
0  False  False  False       False   False  False
1  False  False  False       False   False  False
2  False  False  False       False   False  False
3  False  False  False       False   False  False
4  False  False   True       False    True  False

In [74]:
ex1[ex1['occupation'] == 'Teacher']

id   name   age occupation   salary   city
2   3  Disha  28.0    Teacher  50000.0  Delhi

In [78]:
ex1.sort_values(by='city',ascending=False)

id    name   age occupation   salary     city
1   2  Sarika  30.0   Engineer  80000.0   Mumbai
4   5    Neha   NaN   Engineer      NaN   Mumbai
0   1  Saumya  25.0     Doctor  70000.0    Delhi
2   3   Disha  28.0    Teacher  50000.0    Delhi
3   4    Ravi  22.0     Doctor  72000.0  Chennai

In [81]:
ex1.groupby('occupation')['salary'].mean()

occupation
Doctor      71000.0
Engineer    80000.0
Teacher     50000.0
Name: salary, dtype: float64

In [82]:
ex1.groupby('city').count()

id  name  age  occupation  salary
city                                      
Chennai   1     1    1           1       1
Delhi     2     2    2           2       2
Mumbai    2     2    1           2       1

In [83]:
ex1.fillna(0)

id    name   age occupation   salary     city
0   1  Saumya  25.0     Doctor  70000.0    Delhi
1   2  Sarika  30.0   Engineer  80000.0   Mumbai
2   3   Disha  28.0    Teacher  50000.0    Delhi
3   4    Ravi  22.0     Doctor  72000.0  Chennai
4   5    Neha   0.0   Engineer      0.0   Mumbai

In [86]:
ex1.fillna({'age':32, 'salary':60000},inplace=True)

In [87]:
ex1

id    name   age occupation   salary     city
0   1  Saumya  25.0     Doctor  70000.0    Delhi
1   2  Sarika  30.0   Engineer  80000.0   Mumbai
2   3   Disha  28.0    Teacher  50000.0    Delhi
3   4    Ravi  22.0     Doctor  72000.0  Chennai
4   5    Neha  32.0   Engineer  60000.0   Mumbai

In [88]:
ex1.dropna()

id    name   age occupation   salary     city
0   1  Saumya  25.0     Doctor  70000.0    Delhi
1   2  Sarika  30.0   Engineer  80000.0   Mumbai
2   3   Disha  28.0    Teacher  50000.0    Delhi
3   4    Ravi  22.0     Doctor  72000.0  Chennai
4   5    Neha  32.0   Engineer  60000.0   Mumbai

In [89]:
ex1.rename(columns={'salary':'monthly salary'},inplace=True)

In [91]:
ex1['bonus']=ex1['monthly salary'] * 0.1

In [94]:
ex1

id    name   age occupation  monthly salary     city   bonus  total sal
0   1  Saumya  25.0     Doctor         70000.0    Delhi  7000.0    77000.0
1   2  Sarika  30.0   Engineer         80000.0   Mumbai  8000.0    88000.0
2   3   Disha  28.0    Teacher         50000.0    Delhi  5000.0    55000.0
3   4    Ravi  22.0     Doctor         72000.0  Chennai  7200.0    79200.0
4   5    Neha  32.0   Engineer         60000.0   Mumbai  6000.0    66000.0

In [93]:
ex1['total sal']=ex1['bonus'] + ex1['monthly salary']

In [95]:
ex1.set_index('id')

name   age occupation  monthly salary     city   bonus  total sal
id                                                                     
1   Saumya  25.0     Doctor         70000.0    Delhi  7000.0    77000.0
2   Sarika  30.0   Engineer         80000.0   Mumbai  8000.0    88000.0
3    Disha  28.0    Teacher         50000.0    Delhi  5000.0    55000.0
4     Ravi  22.0     Doctor         72000.0  Chennai  7200.0    79200.0
5     Neha  32.0   Engineer         60000.0   Mumbai  6000.0    66000.0

In [96]:
ex1.reset_index()

index  id    name   age occupation  monthly salary     city   bonus  \
0      0   1  Saumya  25.0     Doctor         70000.0    Delhi  7000.0   
1      1   2  Sarika  30.0   Engineer         80000.0   Mumbai  8000.0   
2      2   3   Disha  28.0    Teacher         50000.0    Delhi  5000.0   
3      3   4    Ravi  22.0     Doctor         72000.0  Chennai  7200.0   
4      4   5    Neha  32.0   Engineer         60000.0   Mumbai  6000.0   

   total sal  
0    77000.0  
1    88000.0  
2    55000.0  
3    79200.0  
4    66000.0

In [99]:
def age_category(age):
    if age <25:
        return 'young'
    elif age <30:
        return 'mid'
    else:
        return 'senior'
    
ex1['age_group']=ex1['age'].apply(age_category)

In [106]:
ex1

id    name   age occupation   salary     city   bonus  total sal age_group  \
0   1  Saumya  25.0     Doctor  70000.0    Delhi  7000.0    77000.0       mid   
1   2  Sarika  30.0   Engineer  80000.0   Mumbai  8000.0    88000.0    senior   
2   3   Disha  28.0    Teacher  50000.0    Delhi  5000.0    55000.0       mid   
3   4    Ravi  22.0     Doctor  72000.0  Chennai  7200.0    79200.0     young   
4   5    Neha  32.0   Engineer  60000.0   Mumbai  6000.0    66000.0    senior   

             profile  
0    Saumya - Doctor  
1  Sarika - Engineer  
2    Disha - Teacher  
3      Ravi - Doctor  
4    Neha - Engineer

In [101]:
ex1['monthly salary'].apply(lambda x:x*x)

0    4.900000e+09
1    6.400000e+09
2    2.500000e+09
3    5.184000e+09
4    3.600000e+09
Name: monthly salary, dtype: float64

In [103]:
ex1.rename(columns={'monthly salary':'salary'},inplace=True)

In [105]:
ex1['profile'] = ex1.apply(lambda row: row['name'] + ' - ' + row['occupation'], axis=1)


In [107]:
ex1.sort_values('profile')

id    name   age occupation   salary     city   bonus  total sal age_group  \
2   3   Disha  28.0    Teacher  50000.0    Delhi  5000.0    55000.0       mid   
4   5    Neha  32.0   Engineer  60000.0   Mumbai  6000.0    66000.0    senior   
3   4    Ravi  22.0     Doctor  72000.0  Chennai  7200.0    79200.0     young   
1   2  Sarika  30.0   Engineer  80000.0   Mumbai  8000.0    88000.0    senior   
0   1  Saumya  25.0     Doctor  70000.0    Delhi  7000.0    77000.0       mid   

             profile  
2    Disha - Teacher  
4    Neha - Engineer  
3      Ravi - Doctor  
1  Sarika - Engineer  
0    Saumya - Doctor

In [109]:
ex1[ex1['id']==1]

id    name   age occupation   salary   city   bonus  total sal age_group  \
0   1  Saumya  25.0     Doctor  70000.0  Delhi  7000.0    77000.0       mid   

           profile  
0  Saumya - Doctor

In [121]:
def find(n):
    try:   
       if n>0 and n<6:
           print(ex1[ex1['id']==n])
       else:
           print("sorry invalid id")
    except Exception as e:
        print(e)        
    finally:
        print("code executed")

In [125]:
find(9)

sorry invalid id
code executed


In [126]:
ex1.to_csv('family.csv', index=False)